# Generated by Django 4.2 on 2023-05-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='Contact',
        ),
    ]
