# Generated by Django 4.2 on 2023-05-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfaApp', '0003_bpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRESSION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolique', models.FloatField(null=True)),
                ('diastolique', models.FloatField(null=True)),
                ('dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
